/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedBrandRouteImport } from './routes/_authenticated/brand'
import { Route as ApiPublicCleanupExportsRouteImport } from './routes/api/public/cleanup-exports'
import { Route as AuthenticatedAdIdEditRouteImport } from './routes/_authenticated/ad.$id.edit'
import { Route as AuthenticatedAdIdExportRouteImport } from './routes/_authenticated/ad.$id.export'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBrandRoute = AuthenticatedBrandRouteImport.update({
  id: '/_authenticated/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCleanupExportsRoute = ApiPublicCleanupExportsRouteImport.update({
  id: '/api/public/cleanup-exports',
  path: '/api/public/cleanup-exports',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdIdEditRoute = AuthenticatedAdIdEditRouteImport.update({
  id: '/_authenticated/ad/$id/edit',
  path: '/ad/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdIdExportRoute = AuthenticatedAdIdExportRouteImport.update({
  id: '/_authenticated/ad/$id/export',
  path: '/ad/$id/export',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/brand': typeof AuthenticatedBrandRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/cleanup-exports': typeof ApiPublicCleanupExportsRoute
  '/ad/$id/edit': typeof AuthenticatedAdIdEditRoute
  '/ad/$id/export': typeof AuthenticatedAdIdExportRoute
}
export interface FileRoutesByTo {
  '/brand': typeof AuthenticatedBrandRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/cleanup-exports': typeof ApiPublicCleanupExportsRoute
  '/ad/$id/edit': typeof AuthenticatedAdIdEditRoute
  '/ad/$id/export': typeof AuthenticatedAdIdExportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/brand': typeof AuthenticatedBrandRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/cleanup-exports': typeof ApiPublicCleanupExportsRoute
  '/_authenticated/ad/$id/edit': typeof AuthenticatedAdIdEditRoute
  '/_authenticated/ad/$id/export': typeof AuthenticatedAdIdExportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/brand'
    | '/'
    | '/api/public/cleanup-exports'
    | '/ad/$id/edit'
    | '/ad/$id/export'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/brand'
    | '/'
    | '/api/public/cleanup-exports'
    | '/ad/$id/edit'
    | '/ad/$id/export'
  id:
    | '__root__'
    | '/_authenticated/brand'
    | '/_authenticated/'
    | '/api/public/cleanup-exports'
    | '/_authenticated/ad/$id/edit'
    | '/_authenticated/ad/$id/export'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedBrandRoute: typeof AuthenticatedBrandRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  ApiPublicCleanupExportsRoute: typeof ApiPublicCleanupExportsRoute
  AuthenticatedAdIdEditRoute: typeof AuthenticatedAdIdEditRoute
  AuthenticatedAdIdExportRoute: typeof AuthenticatedAdIdExportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/brand': {
      id: '/_authenticated/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof AuthenticatedBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cleanup-exports': {
      id: '/api/public/cleanup-exports'
      path: '/api/public/cleanup-exports'
      fullPath: '/api/public/cleanup-exports'
      preLoaderRoute: typeof ApiPublicCleanupExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ad/$id/edit': {
      id: '/_authenticated/ad/$id/edit'
      path: '/ad/$id/edit'
      fullPath: '/ad/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ad/$id/export': {
      id: '/_authenticated/ad/$id/export'
      path: '/ad/$id/export'
      fullPath: '/ad/$id/export'
      preLoaderRoute: typeof AuthenticatedAdIdExportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedBrandRoute: AuthenticatedBrandRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  ApiPublicCleanupExportsRoute: ApiPublicCleanupExportsRoute,
  AuthenticatedAdIdEditRoute: AuthenticatedAdIdEditRoute,
  AuthenticatedAdIdExportRoute: AuthenticatedAdIdExportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
