/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as AdIdEditRouteImport } from './routes/ad.$id.edit'
import { Route as AdIdExportRouteImport } from './routes/ad.$id.export'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AdIdEditRoute = AdIdEditRouteImport.update({
  id: '/ad/$id/edit',
  path: '/ad/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdIdExportRoute = AdIdExportRouteImport.update({
  id: '/ad/$id/export',
  path: '/ad/$id/export',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/ad/$id/edit': typeof AdIdEditRoute
  '/ad/$id/export': typeof AdIdExportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/ad/$id/edit': typeof AdIdEditRoute
  '/ad/$id/export': typeof AdIdExportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/ad/$id/edit': typeof AdIdEditRoute
  '/ad/$id/export': typeof AdIdExportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/brand' | '/ad/$id/edit' | '/ad/$id/export'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/brand' | '/ad/$id/edit' | '/ad/$id/export'
  id: '__root__' | '/' | '/brand' | '/ad/$id/edit' | '/ad/$id/export'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandRoute: typeof BrandRoute
  AdIdEditRoute: typeof AdIdEditRoute
  AdIdExportRoute: typeof AdIdExportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad/$id/edit': {
      id: '/ad/$id/edit'
      path: '/ad/$id/edit'
      fullPath: '/ad/$id/edit'
      preLoaderRoute: typeof AdIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad/$id/export': {
      id: '/ad/$id/export'
      path: '/ad/$id/export'
      fullPath: '/ad/$id/export'
      preLoaderRoute: typeof AdIdExportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandRoute: BrandRoute,
  AdIdEditRoute: AdIdEditRoute,
  AdIdExportRoute: AdIdExportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
