/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as HelpRouteImport } from './routes/help'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAdminsRouteImport } from './routes/_authenticated/admin/admins'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin/clients'
import { Route as AuthenticatedAdminExportsRouteImport } from './routes/_authenticated/admin/exports'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppAccountRouteImport } from './routes/_authenticated/app/account'
import { Route as AuthenticatedAppAdsRouteImport } from './routes/_authenticated/app/ads'
import { Route as AuthenticatedAppBrandRouteImport } from './routes/_authenticated/app/brand'
import { Route as AuthenticatedAppHelpRouteImport } from './routes/_authenticated/app/help'
import { Route as ApiPublicCleanupExportsRouteImport } from './routes/api/public/cleanup-exports'
import { Route as ApiPublicTrialRemindersRouteImport } from './routes/api/public/trial-reminders'
import { Route as AuthenticatedAdminClientsIdRouteImport } from './routes/_authenticated/admin/clients_.$id'
import { Route as AuthenticatedAdminTemplatesIndexRouteImport } from './routes/_authenticated/admin/templates.index'
import { Route as AuthenticatedAdminTemplatesIdRouteImport } from './routes/_authenticated/admin/templates.$id'
import { Route as AuthenticatedAppAccountBillingRouteImport } from './routes/_authenticated/app/account_.billing'
import { Route as AuthenticatedAppAccountMembersRouteImport } from './routes/_authenticated/app/account_.members'
import { Route as AuthenticatedAppAdminSplatRouteImport } from './routes/_authenticated/app/admin.$'
import { Route as AuthenticatedAppTemplatesIndexRouteImport } from './routes/_authenticated/app/templates.index'
import { Route as AuthenticatedAppTemplatesSlugRouteImport } from './routes/_authenticated/app/templates.$slug'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as AuthenticatedAppAdIdEditRouteImport } from './routes/_authenticated/app/ad.$id.edit'
import { Route as AuthenticatedAppAdIdExportRouteImport } from './routes/_authenticated/app/ad.$id.export'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAdminsRoute =
  AuthenticatedAdminAdminsRouteImport.update({
    id: '/admins',
    path: '/admins',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminExportsRoute =
  AuthenticatedAdminExportsRouteImport.update({
    id: '/exports',
    path: '/exports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppAccountRoute = AuthenticatedAppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppAdsRoute = AuthenticatedAppAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppBrandRoute = AuthenticatedAppBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppHelpRoute = AuthenticatedAppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const ApiPublicCleanupExportsRoute = ApiPublicCleanupExportsRouteImport.update({
  id: '/api/public/cleanup-exports',
  path: '/api/public/cleanup-exports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrialRemindersRoute = ApiPublicTrialRemindersRouteImport.update({
  id: '/api/public/trial-reminders',
  path: '/api/public/trial-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminClientsIdRoute =
  AuthenticatedAdminClientsIdRouteImport.update({
    id: '/clients_/$id',
    path: '/clients/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTemplatesIndexRoute =
  AuthenticatedAdminTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTemplatesIdRoute =
  AuthenticatedAdminTemplatesIdRouteImport.update({
    id: '/templates/$id',
    path: '/templates/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAppAccountBillingRoute =
  AuthenticatedAppAccountBillingRouteImport.update({
    id: '/account_/billing',
    path: '/account/billing',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAccountMembersRoute =
  AuthenticatedAppAccountMembersRouteImport.update({
    id: '/account_/members',
    path: '/account/members',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAdminSplatRoute =
  AuthenticatedAppAdminSplatRouteImport.update({
    id: '/admin/$',
    path: '/admin/$',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppTemplatesIndexRoute =
  AuthenticatedAppTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppTemplatesSlugRoute =
  AuthenticatedAppTemplatesSlugRouteImport.update({
    id: '/templates/$slug',
    path: '/templates/$slug',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppAdIdEditRoute =
  AuthenticatedAppAdIdEditRouteImport.update({
    id: '/ad/$id/edit',
    path: '/ad/$id/edit',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAdIdExportRoute =
  AuthenticatedAppAdIdExportRouteImport.update({
    id: '/ad/$id/export',
    path: '/ad/$id/export',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/examples': typeof ExamplesRoute
  '/features': typeof FeaturesRoute
  '/help': typeof HelpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset': typeof ResetRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/exports': typeof AuthenticatedAdminExportsRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/ads': typeof AuthenticatedAppAdsRoute
  '/app/brand': typeof AuthenticatedAppBrandRoute
  '/app/help': typeof AuthenticatedAppHelpRoute
  '/api/public/cleanup-exports': typeof ApiPublicCleanupExportsRoute
  '/api/public/trial-reminders': typeof ApiPublicTrialRemindersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/admin/templates/$id': typeof AuthenticatedAdminTemplatesIdRoute
  '/app/account/billing': typeof AuthenticatedAppAccountBillingRoute
  '/app/account/members': typeof AuthenticatedAppAccountMembersRoute
  '/app/admin/$': typeof AuthenticatedAppAdminSplatRoute
  '/app/templates/$slug': typeof AuthenticatedAppTemplatesSlugRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/admin/templates/': typeof AuthenticatedAdminTemplatesIndexRoute
  '/app/templates/': typeof AuthenticatedAppTemplatesIndexRoute
  '/app/ad/$id/edit': typeof AuthenticatedAppAdIdEditRoute
  '/app/ad/$id/export': typeof AuthenticatedAppAdIdExportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/examples': typeof ExamplesRoute
  '/features': typeof FeaturesRoute
  '/help': typeof HelpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset': typeof ResetRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/blog': typeof BlogIndexRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/exports': typeof AuthenticatedAdminExportsRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/ads': typeof AuthenticatedAppAdsRoute
  '/app/brand': typeof AuthenticatedAppBrandRoute
  '/app/help': typeof AuthenticatedAppHelpRoute
  '/api/public/cleanup-exports': typeof ApiPublicCleanupExportsRoute
  '/api/public/trial-reminders': typeof ApiPublicTrialRemindersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/admin/templates/$id': typeof AuthenticatedAdminTemplatesIdRoute
  '/app/account/billing': typeof AuthenticatedAppAccountBillingRoute
  '/app/account/members': typeof AuthenticatedAppAccountMembersRoute
  '/app/admin/$': typeof AuthenticatedAppAdminSplatRoute
  '/app/templates/$slug': typeof AuthenticatedAppTemplatesSlugRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesIndexRoute
  '/app/templates': typeof AuthenticatedAppTemplatesIndexRoute
  '/app/ad/$id/edit': typeof AuthenticatedAppAdIdEditRoute
  '/app/ad/$id/export': typeof AuthenticatedAppAdIdExportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/examples': typeof ExamplesRoute
  '/features': typeof FeaturesRoute
  '/help': typeof HelpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset': typeof ResetRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/_authenticated/admin/exports': typeof AuthenticatedAdminExportsRoute
  '/_authenticated/app/account': typeof AuthenticatedAppAccountRoute
  '/_authenticated/app/ads': typeof AuthenticatedAppAdsRoute
  '/_authenticated/app/brand': typeof AuthenticatedAppBrandRoute
  '/_authenticated/app/help': typeof AuthenticatedAppHelpRoute
  '/api/public/cleanup-exports': typeof ApiPublicCleanupExportsRoute
  '/api/public/trial-reminders': typeof ApiPublicTrialRemindersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/admin/clients_/$id': typeof AuthenticatedAdminClientsIdRoute
  '/_authenticated/admin/templates/$id': typeof AuthenticatedAdminTemplatesIdRoute
  '/_authenticated/app/account_/billing': typeof AuthenticatedAppAccountBillingRoute
  '/_authenticated/app/account_/members': typeof AuthenticatedAppAccountMembersRoute
  '/_authenticated/app/admin/$': typeof AuthenticatedAppAdminSplatRoute
  '/_authenticated/app/templates/$slug': typeof AuthenticatedAppTemplatesSlugRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/admin/templates/': typeof AuthenticatedAdminTemplatesIndexRoute
  '/_authenticated/app/templates/': typeof AuthenticatedAppTemplatesIndexRoute
  '/_authenticated/app/ad/$id/edit': typeof AuthenticatedAppAdIdEditRoute
  '/_authenticated/app/ad/$id/export': typeof AuthenticatedAppAdIdExportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/examples'
    | '/features'
    | '/help'
    | '/pricing'
    | '/privacy'
    | '/reset'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/admin'
    | '/app'
    | '/blog/$slug'
    | '/invite/$token'
    | '/blog/'
    | '/admin/admins'
    | '/admin/audit'
    | '/admin/clients'
    | '/admin/exports'
    | '/app/account'
    | '/app/ads'
    | '/app/brand'
    | '/app/help'
    | '/api/public/cleanup-exports'
    | '/api/public/trial-reminders'
    | '/admin/'
    | '/app/'
    | '/admin/clients/$id'
    | '/admin/templates/$id'
    | '/app/account/billing'
    | '/app/account/members'
    | '/app/admin/$'
    | '/app/templates/$slug'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/admin/templates/'
    | '/app/templates/'
    | '/app/ad/$id/edit'
    | '/app/ad/$id/export'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/examples'
    | '/features'
    | '/help'
    | '/pricing'
    | '/privacy'
    | '/reset'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/blog/$slug'
    | '/invite/$token'
    | '/blog'
    | '/admin/admins'
    | '/admin/audit'
    | '/admin/clients'
    | '/admin/exports'
    | '/app/account'
    | '/app/ads'
    | '/app/brand'
    | '/app/help'
    | '/api/public/cleanup-exports'
    | '/api/public/trial-reminders'
    | '/admin'
    | '/app'
    | '/admin/clients/$id'
    | '/admin/templates/$id'
    | '/app/account/billing'
    | '/app/account/members'
    | '/app/admin/$'
    | '/app/templates/$slug'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/admin/templates'
    | '/app/templates'
    | '/app/ad/$id/edit'
    | '/app/ad/$id/export'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/blog'
    | '/examples'
    | '/features'
    | '/help'
    | '/pricing'
    | '/privacy'
    | '/reset'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/blog/$slug'
    | '/invite/$token'
    | '/blog/'
    | '/_authenticated/admin/admins'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/exports'
    | '/_authenticated/app/account'
    | '/_authenticated/app/ads'
    | '/_authenticated/app/brand'
    | '/_authenticated/app/help'
    | '/api/public/cleanup-exports'
    | '/api/public/trial-reminders'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/admin/clients_/$id'
    | '/_authenticated/admin/templates/$id'
    | '/_authenticated/app/account_/billing'
    | '/_authenticated/app/account_/members'
    | '/_authenticated/app/admin/$'
    | '/_authenticated/app/templates/$slug'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/admin/templates/'
    | '/_authenticated/app/templates/'
    | '/_authenticated/app/ad/$id/edit'
    | '/_authenticated/app/ad/$id/export'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ExamplesRoute: typeof ExamplesRoute
  FeaturesRoute: typeof FeaturesRoute
  HelpRoute: typeof HelpRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetRoute: typeof ResetRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiPublicCleanupExportsRoute: typeof ApiPublicCleanupExportsRoute
  ApiPublicTrialRemindersRoute: typeof ApiPublicTrialRemindersRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/admins': {
      id: '/_authenticated/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AuthenticatedAdminAdminsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/exports': {
      id: '/_authenticated/admin/exports'
      path: '/exports'
      fullPath: '/admin/exports'
      preLoaderRoute: typeof AuthenticatedAdminExportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/account': {
      id: '/_authenticated/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AuthenticatedAppAccountRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/ads': {
      id: '/_authenticated/app/ads'
      path: '/ads'
      fullPath: '/app/ads'
      preLoaderRoute: typeof AuthenticatedAppAdsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/brand': {
      id: '/_authenticated/app/brand'
      path: '/brand'
      fullPath: '/app/brand'
      preLoaderRoute: typeof AuthenticatedAppBrandRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/help': {
      id: '/_authenticated/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AuthenticatedAppHelpRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/api/public/cleanup-exports': {
      id: '/api/public/cleanup-exports'
      path: '/api/public/cleanup-exports'
      fullPath: '/api/public/cleanup-exports'
      preLoaderRoute: typeof ApiPublicCleanupExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trial-reminders': {
      id: '/api/public/trial-reminders'
      path: '/api/public/trial-reminders'
      fullPath: '/api/public/trial-reminders'
      preLoaderRoute: typeof ApiPublicTrialRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/clients_/$id': {
      id: '/_authenticated/admin/clients_/$id'
      path: '/clients/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AuthenticatedAdminClientsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/templates/': {
      id: '/_authenticated/admin/templates/'
      path: '/templates'
      fullPath: '/admin/templates/'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/templates/$id': {
      id: '/_authenticated/admin/templates/$id'
      path: '/templates/$id'
      fullPath: '/admin/templates/$id'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/app/account_/billing': {
      id: '/_authenticated/app/account_/billing'
      path: '/account/billing'
      fullPath: '/app/account/billing'
      preLoaderRoute: typeof AuthenticatedAppAccountBillingRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/account_/members': {
      id: '/_authenticated/app/account_/members'
      path: '/account/members'
      fullPath: '/app/account/members'
      preLoaderRoute: typeof AuthenticatedAppAccountMembersRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/admin/$': {
      id: '/_authenticated/app/admin/$'
      path: '/admin/$'
      fullPath: '/app/admin/$'
      preLoaderRoute: typeof AuthenticatedAppAdminSplatRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/templates/': {
      id: '/_authenticated/app/templates/'
      path: '/templates'
      fullPath: '/app/templates/'
      preLoaderRoute: typeof AuthenticatedAppTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/templates/$slug': {
      id: '/_authenticated/app/templates/$slug'
      path: '/templates/$slug'
      fullPath: '/app/templates/$slug'
      preLoaderRoute: typeof AuthenticatedAppTemplatesSlugRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/ad/$id/edit': {
      id: '/_authenticated/app/ad/$id/edit'
      path: '/ad/$id/edit'
      fullPath: '/app/ad/$id/edit'
      preLoaderRoute: typeof AuthenticatedAppAdIdEditRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/ad/$id/export': {
      id: '/_authenticated/app/ad/$id/export'
      path: '/ad/$id/export'
      fullPath: '/app/ad/$id/export'
      preLoaderRoute: typeof AuthenticatedAppAdIdExportRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdminsRoute: typeof AuthenticatedAdminAdminsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRoute
  AuthenticatedAdminExportsRoute: typeof AuthenticatedAdminExportsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminClientsIdRoute: typeof AuthenticatedAdminClientsIdRoute
  AuthenticatedAdminTemplatesIdRoute: typeof AuthenticatedAdminTemplatesIdRoute
  AuthenticatedAdminTemplatesIndexRoute: typeof AuthenticatedAdminTemplatesIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdminsRoute: AuthenticatedAdminAdminsRoute,
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRoute,
    AuthenticatedAdminExportsRoute: AuthenticatedAdminExportsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminClientsIdRoute: AuthenticatedAdminClientsIdRoute,
    AuthenticatedAdminTemplatesIdRoute: AuthenticatedAdminTemplatesIdRoute,
    AuthenticatedAdminTemplatesIndexRoute:
      AuthenticatedAdminTemplatesIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppAccountRoute: typeof AuthenticatedAppAccountRoute
  AuthenticatedAppAdsRoute: typeof AuthenticatedAppAdsRoute
  AuthenticatedAppBrandRoute: typeof AuthenticatedAppBrandRoute
  AuthenticatedAppHelpRoute: typeof AuthenticatedAppHelpRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAccountBillingRoute: typeof AuthenticatedAppAccountBillingRoute
  AuthenticatedAppAccountMembersRoute: typeof AuthenticatedAppAccountMembersRoute
  AuthenticatedAppAdminSplatRoute: typeof AuthenticatedAppAdminSplatRoute
  AuthenticatedAppTemplatesSlugRoute: typeof AuthenticatedAppTemplatesSlugRoute
  AuthenticatedAppTemplatesIndexRoute: typeof AuthenticatedAppTemplatesIndexRoute
  AuthenticatedAppAdIdEditRoute: typeof AuthenticatedAppAdIdEditRoute
  AuthenticatedAppAdIdExportRoute: typeof AuthenticatedAppAdIdExportRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppAccountRoute: AuthenticatedAppAccountRoute,
  AuthenticatedAppAdsRoute: AuthenticatedAppAdsRoute,
  AuthenticatedAppBrandRoute: AuthenticatedAppBrandRoute,
  AuthenticatedAppHelpRoute: AuthenticatedAppHelpRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAccountBillingRoute: AuthenticatedAppAccountBillingRoute,
  AuthenticatedAppAccountMembersRoute: AuthenticatedAppAccountMembersRoute,
  AuthenticatedAppAdminSplatRoute: AuthenticatedAppAdminSplatRoute,
  AuthenticatedAppTemplatesSlugRoute: AuthenticatedAppTemplatesSlugRoute,
  AuthenticatedAppTemplatesIndexRoute: AuthenticatedAppTemplatesIndexRoute,
  AuthenticatedAppAdIdEditRoute: AuthenticatedAppAdIdEditRoute,
  AuthenticatedAppAdIdExportRoute: AuthenticatedAppAdIdExportRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ExamplesRoute: ExamplesRoute,
  FeaturesRoute: FeaturesRoute,
  HelpRoute: HelpRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetRoute: ResetRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiPublicCleanupExportsRoute: ApiPublicCleanupExportsRoute,
  ApiPublicTrialRemindersRoute: ApiPublicTrialRemindersRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
